### ISSUE TITLE
Allow empty values in dme_record

### ISSUE THREAD

**Issue by emsearcy** [DNSMadeEasy/terraform-provider-dme#10]
Please note this is not exactly the same as issue #3 which is for empty *names*, not empty *values*.

### Terraform Version
0.11.1

### Affected Resource(s)
- dme_record

### Terraform Configuration Files
```hcl
resource "dme_record" "www" {
  domainid    = "1234"
  name        = "www"
  type        = "CNAME"
  value       = ""
  ttl         = 3600
  gtdLocation = "DEFAULT"
}
```

### Expected Behavior
Terraform should create a "www" CNAME record with an empty value, which is how DNS Made Easy represents the current domain's apex (naked domain).

### Actual Behavior
500 error from DNS Made Easy because the "value" parameter is missing.

### References
This is closely related to issue #3 and PR #7, except with the *value* parameter instead of the *name* parameters.

I made a slight addition to PR #7 at emsearcy/terraform-provider-dme@513fb173 but I haven't made a PR yet because I wanted to add a test, similar to the check for empty names.

**Comment by nkatarmal-crest** [comment]
Closing this issue, as provider has been redeveloped and released.
