### ISSUE TITLE
Environment variable support for API & Secret keys

### ISSUE THREAD

**Issue by case** [DNSMadeEasy/terraform-provider-dme#19]
Could you add support for setting API and Secret keys via environment variables? I see this in your `provider_test.go` file already, but not in the actual provider functionality.

**Comment by nkatarmal-crest** [comment]
It's already there, name of env variables are `apikey` and `secretkey `.

**Comment by robertomoutinho** [comment]
https://github.com/DNSMadeEasy/terraform-provider-dme/blob/0f02d24c54c004328b0dd121dfc31f3927afa0b5/dme/provider.go#L18

In theory the `EnvDefaultFunc` should be able to capture the environment variable `apikey` and `secretkey`... it would be great if they updated their docs and followed the uppercase convention when naming their env var inputs
